### ISSUE TITLE
Toggle QA reporting

### ISSUE THREAD

**Issue by raphaelmazor** [SCCWRP/PHAB#4]
Can you add an argument (default =True) about including QA statistics in the output of the reporting module?

If set to true, proceed with the IPI reporting as-is.
If set to false, not only should you not calculate the QA component of the report, but you should also suppress the error checks on the following variables:
XC
PCT_POOL
XFC_ALG
PCT_SA

**Comment by fawda123** [comment]
From @raphaelmazor previous issue: 

I made a mistake in my previous request:

Diversity (H) and evenness (Ev) metrics can be zero (if there's only one "species" in a sample), but they can't be negative. Can you refine the the QA checks accordingly?

**Comment by fawda123** [comment]
@raphaelmazor 

QA toggle ef4de4fee960a26e08ed688ac673c4499d6a10df

Error checks on XC, PCT_POOL, XFC_ALG, and PCT_SA removed if QA is false, otherwise they are checked for containing negative values.  All diversity and evenness variables were already checked for negative values, they are not flagged if they contain zeroes.  dbaf55fce367c8ef86ce05ade0533bf046dae353
